// <auto-generated />
using DictionaryAssistantMVC.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DictionaryAssistantMVC.Migrations
{
    [DbContext(typeof(DictionaryContext))]
    [Migration("20200901175624_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("DictionaryAssistantMVC.Models.Letter", b =>
                {
                    b.Property<int>("LetterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AverageCharacters")
                        .HasColumnType("integer");

                    b.Property<char>("Character")
                        .HasColumnType("character(1)");

                    b.Property<int>("CountBeginningWith")
                        .HasColumnType("integer");

                    b.Property<int>("CountEndingWith")
                        .HasColumnType("integer");

                    b.HasKey("LetterID");

                    b.ToTable("Letters");
                });

            modelBuilder.Entity("DictionaryAssistantMVC.Models.Word", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("LetterID")
                        .HasColumnType("integer");

                    b.Property<string>("TheWord")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("LetterID");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("DictionaryAssistantMVC.Models.Word", b =>
                {
                    b.HasOne("DictionaryAssistantMVC.Models.Letter", "Letter")
                        .WithMany("Word")
                        .HasForeignKey("LetterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
